name: frontend_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  build_runner: ^2.10.5
  dio: ^5.9.1
  envied: ^1.3.2
  envied_generator: ^1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  http: ^1.6.0
  image_picker: ^1.2.1
  json_serializable: ^6.12.0
  mockito: ^5.6.3

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
